import { describe, expect, it, vi } from "vitest";
import { Core } from "../src/core.js";
import { HybridLoader } from "../src/hybrid-loader.js";
import { hlsManifestParser } from "../src/manifest/hls.js";
import {
  computeInfoHash,
  computeStreamIdentityHash,
  identityProperties,
} from "../src/stream-identity.js";
import { CoreConfig, StreamSwarmIdBuilderContext } from "../src/types.js";
import {
  HLS_LIVE_NO_PDT_REFRESH_1,
  HLS_LIVE_NO_PDT_REFRESH_2,
  HLS_MASTER_WITH_AUDIO,
  HLS_MEDIA_VOD_BYTERANGE,
} from "./fixtures/index.js";

const MANIFEST_URL = "https://example.com/hls/master.m3u8";
const VIDEO_1080 = "https://example.com/hls/video/1080p/index.m3u8";
const VIDEO_360 = "https://example.com/hls/video/360p/index.m3u8";
const AUDIO_EN = "https://example.com/hls/audio/en/index.m3u8";
const AUDIO_DE = "https://example.com/hls/audio/de/index.m3u8";
const MEDIA_URL = "https://cdn.example/vod/index.m3u8";

// Identity of the 1080p variant of HLS_MASTER_WITH_AUDIO, as the HLS parser
// reads it: the video codec alone (audio belongs to the rendition), resolution,
// frame rate, video range — and no bitrate, since no other variant shares
// those. Literals generated by the implementation and frozen, like the
// vectors in stream-identity.test.ts.
const IDENTITY_1080 = "Kp1jPi76p5kmI4USY6Cdfgf8ljo=";
const INFOHASH_1080 = "MF+Ke1DXhaebi+f+8zmv";

/** Streams enter the core only through manifests. */
function createCore(config?: Partial<CoreConfig>) {
  const core = new Core({ ...config, manifestParsers: [hlsManifestParser] });
  core.processManifest({
    url: `${MANIFEST_URL}?token=abc`,
    data: HLS_MASTER_WITH_AUDIO,
  });
  return core;
}

describe("stream registration from manifests", () => {
  it("registers every variant and rendition the master declares, in order", () => {
    const core = createCore();
    expect(core.getStreams().map((s) => [s.runtimeId, s.type])).toEqual([
      [VIDEO_1080, "main"],
      [VIDEO_360, "main"],
      [AUDIO_EN, "secondary"],
      [AUDIO_DE, "secondary"],
    ]);
  });

  it("computes the default identity matching the golden vectors", () => {
    const stream = createCore().getStream(VIDEO_1080);
    expect(stream).toBeDefined();
    expect(stream?.swarmId).toBe(MANIFEST_URL); // query parameters stripped
    expect(stream?.identityHash).toBe(IDENTITY_1080);
    expect(stream?.streamSwarmId).toBe(
      `v3-${MANIFEST_URL}-main-${IDENTITY_1080}`,
    );
    expect(stream?.infoHash).toBe(INFOHASH_1080);
    // Reproducible from the streams' properties by the exported rule.
    const streams = createCore().getStreams();
    const inputs = identityProperties(streams);
    streams.forEach((s, i) => {
      expect(s.identityHash).toBe(computeStreamIdentityHash(inputs[i]));
    });
    expect(inputs[0].bitrate).toBeUndefined();
  });

  it("names the swarm after the first manifest unless told otherwise", () => {
    const core = new Core({ manifestParsers: [hlsManifestParser] });
    core.setManifestResponseUrl("https://origin.example/master.m3u8?sig=1");
    core.processManifest({ url: MANIFEST_URL, data: HLS_MASTER_WITH_AUDIO });
    expect(core.getStream(VIDEO_1080)?.swarmId).toBe(
      "https://origin.example/master.m3u8",
    );
  });

  it("prefers the configured swarmId over the manifest URL", () => {
    const stream = createCore({ swarmId: "my-swarm" }).getStream(VIDEO_1080);
    expect(stream?.swarmId).toBe("my-swarm");
    expect(stream?.streamSwarmId).toBe(`v3-my-swarm-main-${IDENTITY_1080}`);
    expect(stream?.infoHash).toBe(
      computeInfoHash(`v3-my-swarm-main-${IDENTITY_1080}`),
    );
  });

  it("uses the streamSwarmIdBuilder output verbatim", () => {
    const contexts: StreamSwarmIdBuilderContext[] = [];
    const core = createCore({
      streamSwarmIdBuilder: (context) => {
        contexts.push(context);
        return `custom-${context.runtimeId}`;
      },
    });

    const stream = core.getStream(VIDEO_1080);
    expect(stream?.streamSwarmId).toBe(`custom-${VIDEO_1080}`);
    expect(stream?.infoHash).toBe(computeInfoHash(`custom-${VIDEO_1080}`));

    const context = contexts.find((c) => c.runtimeId === VIDEO_1080);
    expect(context).toMatchObject({
      swarmId: MANIFEST_URL,
      streamType: "main",
      identityHash: IDENTITY_1080,
      defaultStreamSwarmId: `v3-${MANIFEST_URL}-main-${IDENTITY_1080}`,
      peerProtocolVersion: "v3",
    });
    expect(context?.properties).toMatchObject({
      bitrate: 4521000,
      width: 1920,
      height: 1080,
    });
  });

  it("supports building on the default stream swarm ID from the context", () => {
    const core = createCore({
      streamSwarmIdBuilder: ({ defaultStreamSwarmId }) =>
        `tenant-a-${defaultStreamSwarmId}`,
    });
    const expectedId = `tenant-a-v3-${MANIFEST_URL}-main-${IDENTITY_1080}`;
    const stream = core.getStream(VIDEO_1080);
    expect(stream?.streamSwarmId).toBe(expectedId);
    expect(stream?.infoHash).toBe(computeInfoHash(expectedId));
  });

  it("falls back to the default derivation when the builder returns undefined", () => {
    const core = createCore({ streamSwarmIdBuilder: () => undefined });
    expect(core.getStream(VIDEO_1080)?.infoHash).toBe(INFOHASH_1080);
  });

  it("reports a builder that returns an empty or non-string value, once per stream", () => {
    for (const builderResult of ["", 42 as unknown as string]) {
      const core = new Core({
        manifestParsers: [hlsManifestParser],
        streamSwarmIdBuilder: () => builderResult,
      });
      const onRegistrationError = vi.fn();
      core.addEventListener("onStreamRegistrationError", onRegistrationError);

      core.processManifest({ url: MANIFEST_URL, data: HLS_MASTER_WITH_AUDIO });
      // A refresh must not report the same failures again.
      core.processManifest({ url: MANIFEST_URL, data: HLS_MASTER_WITH_AUDIO });

      expect(core.getStreams()).toEqual([]);
      expect(onRegistrationError).toHaveBeenCalledTimes(4);
      const { error } = onRegistrationError.mock.calls[0][0] as {
        error: Error;
      };
      expect(error.message).toMatch(/non-empty string/);
    }
  });

  it("rejects a stream whose custom swarm ID collides with a different identity", () => {
    const onStreamAdded = vi.fn();
    const onRegistrationError = vi.fn();
    const core = new Core({
      manifestParsers: [hlsManifestParser],
      streamSwarmIdBuilder: () => "same-key",
    });
    core.addEventListener("onStreamAdded", onStreamAdded);
    core.addEventListener("onStreamRegistrationError", onRegistrationError);
    core.processManifest({ url: MANIFEST_URL, data: HLS_MASTER_WITH_AUDIO });

    // The first stream takes the key; every later stream collides with it.
    expect(core.getStreams().map((s) => s.runtimeId)).toEqual([VIDEO_1080]);
    expect(onStreamAdded).toHaveBeenCalledTimes(1);
    expect(onRegistrationError).toHaveBeenCalledTimes(3);
    const { runtimeId, error } = onRegistrationError.mock.calls[0][0] as {
      runtimeId: string;
      error: Error;
    };
    expect(runtimeId).toBe(VIDEO_360);
    expect(error.message).toMatch(/same stream swarm ID/);
  });

  it("rejects a builder that collapses different stream types onto one ID", () => {
    // Keyed on bitrate alone, the 360p variant (blank metadata, bitrate 0)
    // and the audio renditions (bitrate 0) merge into one swarm — peers
    // would then swap audio and video segments.
    const onRegistrationError = vi.fn();
    const core = createCore({
      streamSwarmIdBuilder: ({ properties }) => `k-${properties.bitrate ?? 0}`,
    });
    core.addEventListener("onStreamRegistrationError", onRegistrationError);
    core.processManifest({ url: MANIFEST_URL, data: HLS_MASTER_WITH_AUDIO });

    expect(core.getStream(VIDEO_360)).toBeDefined();
    expect(core.getStream(AUDIO_EN)).toBeUndefined();
    expect(core.getStream(AUDIO_DE)).toBeUndefined();
  });

  it("registers a stream only once and fires onStreamAdded once", () => {
    const core = new Core({ manifestParsers: [hlsManifestParser] });
    const onStreamAdded = vi.fn();
    core.addEventListener("onStreamAdded", onStreamAdded);

    core.processManifest({ url: MANIFEST_URL, data: HLS_MASTER_WITH_AUDIO });
    core.processManifest({ url: MANIFEST_URL, data: HLS_MASTER_WITH_AUDIO });

    expect(onStreamAdded).toHaveBeenCalledTimes(4);
    const { stream } = onStreamAdded.mock.calls[0][0];
    expect(stream.infoHash).toBe(INFOHASH_1080);

    // The payload is a snapshot of the registered stream's identity,
    // detached from the core's internal stream state.
    const registered = core.getStream(VIDEO_1080);
    expect(stream).not.toBe(registered);
    expect("segments" in stream).toBe(false);
    expect(stream).toEqual(registered);
  });

  it("freezes stream properties at registration", () => {
    const stream = createCore().getStream(VIDEO_1080);
    expect(Object.isFrozen(stream?.properties)).toBe(true);
  });

  it("returns detached snapshots from getStream and getStreams", () => {
    const core = createCore();
    const fromGetStream = core.getStream(VIDEO_1080);
    const fromGetStreams = core.getStreams()[0];

    // No path into the core's internal segment registry.
    expect(fromGetStream && "segments" in fromGetStream).toBe(false);
    expect("segments" in fromGetStreams).toBe(false);

    // A fresh snapshot per call: equal by value, not shared by reference.
    expect(fromGetStream).not.toBe(core.getStream(VIDEO_1080));
    expect(fromGetStream).toEqual(core.getStream(VIDEO_1080));
    expect(fromGetStreams).not.toBe(fromGetStream);
    expect(fromGetStreams).toEqual(fromGetStream);
  });

  it("forgets everything on destroy", () => {
    const core = createCore();
    core.destroy();
    expect(core.getStreams()).toEqual([]);
  });
});

describe("segment lookup", () => {
  const MEDIA_MP4 = "https://cdn.example/vod/media.mp4";
  const INIT_MP4 = "https://cdn.example/vod/init.mp4";

  function createVodCore(config?: Partial<CoreConfig>) {
    const core = new Core({ ...config, manifestParsers: [hlsManifestParser] });
    core.processManifest({ url: MEDIA_URL, data: HLS_MEDIA_VOD_BYTERANGE });
    return core;
  }

  it("resolves a request by URL and inclusive byte range", () => {
    const core = createVodCore();
    expect(core.hasSegment(MEDIA_MP4, { start: 600, end: 1599 })).toBe(true);
    expect(core.isSegmentLoadable(MEDIA_MP4, { start: 600, end: 1599 })).toBe(
      true,
    );
    // The range is part of the key: the same file at another offset is
    // another segment, and the whole file is nothing the registry knows.
    expect(core.hasSegment(MEDIA_MP4, { start: 600, end: 1600 })).toBe(false);
    expect(core.hasSegment(MEDIA_MP4)).toBe(false);
  });

  it("ignores a telemetry query parameter the player appended", () => {
    const core = createVodCore();
    expect(
      core.isSegmentLoadable(`${MEDIA_MP4}?CMCD=bl%3D2000`, {
        start: 600,
        end: 1599,
      }),
    ).toBe(true);
  });

  it("reports a miss for an unknown URL, but not for an initialization segment", () => {
    const core = createVodCore();
    const onMiss = vi.fn();
    core.addEventListener("onSegmentRegistryMiss", onMiss);

    expect(core.isSegmentLoadable(INIT_MP4, { start: 0, end: 599 })).toBe(
      false,
    );
    expect(onMiss).not.toHaveBeenCalled();

    expect(
      core.isSegmentLoadable("https://cdn.example/vod/other.mp4", {
        start: 0,
        end: 99,
      }),
    ).toBe(false);
    expect(onMiss).toHaveBeenCalledTimes(1);
    expect(onMiss.mock.calls[0][0]).toEqual({
      url: "https://cdn.example/vod/other.mp4",
      byteRange: { start: 0, end: 99 },
    });
  });

  it("refuses a known segment when P2P is disabled for its stream type, without a miss", () => {
    const core = createVodCore({ mainStream: { isP2PDisabled: true } });
    const onMiss = vi.fn();
    core.addEventListener("onSegmentRegistryMiss", onMiss);

    expect(core.hasSegment(MEDIA_MP4, { start: 600, end: 1599 })).toBe(true);
    expect(core.isSegmentLoadable(MEDIA_MP4, { start: 600, end: 1599 })).toBe(
      false,
    );
    expect(onMiss).not.toHaveBeenCalled();
  });

  it("supports the swarmId-only configuration end to end", () => {
    // A custom integration may configure swarmId; the manifest URL is then
    // never consulted for identity, but segments must still be loadable.
    const core = createVodCore({ swarmId: "my-swarm" });
    expect(core.getStream(MEDIA_URL)?.swarmId).toBe("my-swarm");
    expect(core.isSegmentLoadable(MEDIA_MP4, { start: 600, end: 1599 })).toBe(
      true,
    );
  });

  it("follows a sliding live window and keeps the stream's identity", () => {
    const core = new Core({ manifestParsers: [hlsManifestParser] });
    const url = "https://cdn.example/live/index.m3u8";
    core.processManifest({ url, data: HLS_LIVE_NO_PDT_REFRESH_1 });
    const infoHashBefore = core.getStream(url)?.infoHash;
    expect(core.hasSegment("https://cdn.example/live/seg100.ts")).toBe(true);

    core.processManifest({ url, data: HLS_LIVE_NO_PDT_REFRESH_2 });
    expect(core.hasSegment("https://cdn.example/live/seg100.ts")).toBe(false);
    expect(core.hasSegment("https://cdn.example/live/seg106.ts")).toBe(true);
    expect(core.getStream(url)?.infoHash).toBe(infoHashBefore);
  });

  it("derives the live state from the manifest", () => {
    const peek = (core: Core) =>
      (core as unknown as { streamDetails: { isLive: boolean } }).streamDetails
        .isLive;

    const live = new Core({ manifestParsers: [hlsManifestParser] });
    live.processManifest({
      url: "https://cdn.example/live/index.m3u8",
      data: HLS_LIVE_NO_PDT_REFRESH_1,
    });
    expect(peek(live)).toBe(true);

    expect(peek(createVodCore())).toBe(false);
  });

  it("rejects loading a segment the registry does not know", async () => {
    const core = createVodCore();
    await expect(
      core.loadSegment("https://cdn.example/vod/other.mp4"),
    ).rejects.toThrow(/not in the registry/);
  });

  /**
   * A core whose segment storage stays half-initialized until the test
   * releases it: the window in which a request has entered `loadSegment` and
   * has no loader to carry an abort.
   */
  function createCoreWithHeldStorage() {
    let release!: () => void;
    const held = new Promise<void>((resolve) => (release = resolve));
    const storage = {
      initialize: () => held,
      setSegmentChangeCallback: () => undefined,
      hasSegment: () => false,
      getSegmentData: () => Promise.resolve(undefined),
      onSegmentRequested: () => undefined,
      onPlaybackUpdated: () => undefined,
      storeSegment: () => Promise.resolve(),
      getUsage: () => ({ totalCapacity: 100, usedCapacity: 0 }),
      destroy: () => undefined,
    };
    const core = createVodCore({
      customSegmentStorageFactory: () => storage as never,
    });
    return { core, release };
  }

  const settle = () => new Promise((resolve) => setTimeout(resolve, 0));

  it("aborts a request that is still waiting for the segment storage", async () => {
    const { core, release } = createCoreWithHeldStorage();
    const byteRange = { start: 600, end: 1599 };
    const loading = core.loadSegment(MEDIA_MP4, { byteRange });
    await settle();

    // No loader exists yet to carry the abort; the request takes it itself.
    core.abortSegmentLoading(MEDIA_MP4, byteRange);
    release();
    await expect(loading).rejects.toMatchObject({ type: "aborted" });
  });

  it("aborts requests waiting for the segment storage when the core is destroyed", async () => {
    const { core, release } = createCoreWithHeldStorage();
    const byteRange = { start: 600, end: 1599 };
    const loading = core.loadSegment(MEDIA_MP4, { byteRange });
    await settle();

    core.destroy();
    release();
    await expect(loading).rejects.toMatchObject({ type: "aborted" });
  });

  it("fails a request whose storage throws as it starts, rather than hanging it", async () => {
    // A custom storage is the integrator's code; whatever it does, the
    // request has to settle, or the player waits on a promise for ever.
    const storage = {
      initialize: () => Promise.resolve(),
      setSegmentChangeCallback: () => undefined,
      onSegmentRequested: () => {
        throw new Error("storage is broken");
      },
      hasSegment: () => false,
      getSegmentData: () => Promise.resolve(undefined),
      getStoredSegmentIds: () => [],
      onPlaybackUpdated: () => undefined,
      storeSegment: () => Promise.resolve(),
      getUsage: () => ({ totalCapacity: 100, usedCapacity: 0 }),
      destroy: () => undefined,
    };
    const core = createVodCore({
      customSegmentStorageFactory: () => storage as never,
    });
    // HybridLoader schedules its prefetch timer on `window`.
    vi.stubGlobal("window", globalThis);

    const outcome = await Promise.race([
      core
        .loadSegment(MEDIA_MP4, { byteRange: { start: 600, end: 1599 } })
        .then(
          () => "resolved" as unknown,
          (error: unknown) => error,
        ),
      new Promise((resolve) => setTimeout(() => resolve("never settled"), 200)),
    ]);
    expect(outcome).toMatchObject({ type: "failed" });
    vi.unstubAllGlobals();
    core.destroy();
  });

  it("fails a request whose loader throws before it can report anything", async () => {
    // The backstop for a throw no loader handled: without it the promise
    // stays pending and the abort listener stays on the signal.
    const core = createVodCore();
    vi.stubGlobal("window", globalThis);
    vi.spyOn(HybridLoader.prototype, "loadSegment").mockRejectedValueOnce(
      new Error("loader is broken"),
    );

    await expect(
      core.loadSegment(MEDIA_MP4, { byteRange: { start: 600, end: 1599 } }),
    ).rejects.toMatchObject({ type: "failed" });

    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    core.destroy();
  });

  it("rejects an already-aborted load before touching any loader", async () => {
    const core = createVodCore();
    const controller = new AbortController();
    controller.abort();
    await expect(
      core.loadSegment(MEDIA_MP4, {
        byteRange: { start: 600, end: 1599 },
        signal: controller.signal,
      }),
    ).rejects.toMatchObject({ type: "aborted" });
  });
});
