name: NPM Publish

on:
  push:
    tags:
      - "*"

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          export TAG=$VERSION
          node scripts/update-versions.js

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add package.json
          git commit -m "Update version to ${{ steps.get_version.outputs.VERSION }}"
          git push

      - name: Build
        run: pnpm run build

      - name: Pack Packages
        run: pnpm run pack-packages

  publish:
    needs: setup_and_build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - p2p-media-loader-core
          - p2p-media-loader-hlsjs
          - p2p-media-loader-shaka
    steps:
      - uses: actions/checkout@v4

      - name: Get package version
        id: get_version
        run: |
          echo "PACKAGE_VERSION=$(jq -r '.version' ./packages/${{ matrix.package }}/package.json)" >> $GITHUB_ENV

      - name: Verify .tgz File Path
        run: echo "./packages/${{ matrix.package }}-${{ env.PACKAGE_VERSION }}.tgz"
        working-directory: ./packages/${{ matrix.package }}
